services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Metabolism\WordpressBundle\ArgumentResolver\PostsValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\ArgumentResolver\PostValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\ArgumentResolver\TermValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\ArgumentResolver\UserValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Controller/'
      - '../src/Entity/'
      - '../src/Extension/'
      - '../src/Factory/'
      - '../src/Helper/'
      - '../src/Loader/'
      - '../src/Plugin/'
      - '../src/Provider/'
      - '../src/Traits/'
